theme = "catppuccin_macchiato"

[editor]
true-color = true
#trim-trailing-whitespace = true

[editor.soft-wrap]
enable = true

# Also search for hidden files/folders with space + f
[editor.file-picker]
hidden = false

# Change cursor shape when in insert mode
[editor.cursor-shape]
insert = "bar"
select = "underline"

# In normal mode use escape to clear selection (as well as default ;)
# and also clear multiple cursors (as well as default ,)
# https://www.youtube.com/watch?v=aiSI6vdZWgE
[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
# show where the spaces are (toggle)
F1 = ":toggle whitespace.render all none"
# uppercase
"A-c" = "switch_to_uppercase"

# [editor.statusline]
# left = ["mode", "spinner"]
# center = ["file-name"]
# right = ["diagnostics", "file-type"]
# separator = "â”‚"
# mode.normal = "NORMAL"
# mode.insert = "INSERT"
# mode.select = "SELECT"
# diagnostics = ["warning", "error"]
# workspace-diagnostics = ["warning", "error"]
